### ISSUE TITLE
Error with pulling villas node from windows machine

### ISSUE THREAD

**Issue by edoardo-dedin** [VILLASframework/node#631]
Running `docker run --privileged registry.git.rwth-aachen.de/acs/public/villas/node` on windows powershell (with docker desktop running) I get the following error:

`docker: manifest for registry.git.rwth-aachen.de/acs/public/villas/node:latest not found: manifest unknown: manifest unknown.`

**Comment by stv0g** [comment]
Hi @edoardo-dedin,

can you try again? I fixed the missing image..

**Comment by edoardo-dedin** [comment]
Hi @stv0g,

now is working. Thank you for fixing it!
