### ISSUE TITLE
Image crashing on startup

### ISSUE THREAD

**Issue by iripiri** [VILLASframework/node#639]
The image registry.git.rwth-aachen.de/acs/public/villas/node is crashing with error `exec /app/bin/villas: exec format error`
According to [this website](https://www.starlanguageblog.com/cannot-execute-binary-file-exec-format-error/), there are several lpossible reasons to this:
- the binary is compiled for a different version of your OS
- the binary is created with another compiler.
- the file is corrupt.
- the operating system doesn’t support executables in that format.
(this is happening in different setups, Openstack & minikube/helm)

**Comment by stv0g** [comment]
Oh okay :( Its possible that I pushed a version of the image for `linux/arm64` as my laptop is a 64-bit ARM system :(

The CI-built images are build for multiple platforms and then combined with a Manifest:

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

There is also a part of our CI pipeline which creates such multi-platform manifests for the `latest` tag.
Can you try to trigger this pipeline?

**Comment by stv0g** [comment]
@iripiri Did you have a chance to check it?

**Comment by iripiri** [comment]
Hi @stv0g, I didn't manage to run the pipeline, I do not have sufficient permission. Did you mean I should run the pipeline via the Web-UI in GitLab, or is there another way I can try?

**Comment by windrad6** [comment]
We now have the permissions. That solved the problem.
