### ISSUE TITLE
Make sure villas-graph is installed and build CMake 

### ISSUE THREAD

**Issue by stv0g** [VILLASframework/node#658]
We also need to figure out why this error has not been caught earlier.

I assume that we fail to detect the Graphviz libraries here:
https://github.com/VILLASframework/node/blob/4fa688b9ce7ec827d6571bcf5122fdc6a48263f2/CMakeLists.txt#L162

Looking at the log of the latest successful build indicates that the Graphviz support is enabled:

```
 * GRAPHVIZ, Build with Graphviz support
 ```

Source: https://git.rwth-aachen.de/acs/public/villas/node/-/jobs/3740905

But the villas-graph executable does not seem to be included in the image:

```
$ docker run registry.git.rwth-aachen.de/acs/public/villas/node:master graph
/app/bin/villas: line 38: exec: villas-graph: not found
```

_Originally posted by @stv0g in https://github.com/VILLASframework/node/issues/654#issuecomment-1591237745_

**Comment by stv0g** [comment]
I see why its not installed:

https://github.com/VILLASframework/node/blob/4fa688b9ce7ec827d6571bcf5122fdc6a48263f2/src/CMakeLists.txt#L44-L47

is missing

```cmake
list(APPEND SRCS villas-graph)
```

Otherwise it does not get installed by CMake's install target.

**Comment by PJungkamp** [comment]
`villas-zmq-keygen` seems to be missing too.

```C
if(LIBZMQ_FOUND)
    add_executable(villas-zmq-keygen villas-zmq-keygen.cpp)
    target_link_libraries(villas-zmq-keygen PUBLIC villas-common PkgConfig::LIBZMQ)
    
    list(APPEND SRC villas-zmq-keygen)
endif()
```

There's a typo. `SRC` should be `SRCS`.
