### ISSUE TITLE
A VILLASnode install using WITHOUT_GPL includes the villas-zmq-keygen helper under LGPL3+

### ISSUE THREAD

**Issue by PJungkamp** [VILLASframework/node#709]

**Comment by stv0g** [comment]
libzmq is now licensed under MPL-2.0: https://github.com/zeromq/libzmq

Hence, I would say we are fine here. The `villas-zmq-keygen` also does not contain any copyrightable code by external people.

I will close this issue and track this as https://github.com/VILLASframework/documentation/issues/75  to update the license in our docs.
