### ISSUE TITLE
Inconsistent indentation and trailing whitespace

### ISSUE THREAD

**Issue by PJungkamp** [VILLASframework/node#713]
Many configuration files (both json and conf), as well as lua/txt/... files are still idented using tabs and often contain newlines.

- [ ] Use the same indentation style for both .json and .conf files and apply it consistently to our current files in `etc/`.
- [ ] Unify spaces vs. tabs project wide.
- [ ] Remove tabs in .cpp/.hpp file comments.

@stv0g What is your opinion on this?

**Comment by stv0g** [comment]
I think its a good idea. But I honestly dont want to spent more time myself on code maintenance for a few weeks. The REUSE and clang-format stuff was enough :D

If you like, please feel free to go ahead :)
