### ISSUE TITLE
Value array seems to be empty

### ISSUE THREAD

**Issue by al3xa23** [VILLASframework/node#782]
Hi, 

I want to parse data from VILLASnode to a Python script. I use udp socket between VILLASnode and Python and data format protobuf. 
It worked some months ago. Now, I tried to reuse it again, but I get the error
```
Traceback (most recent call last):
 msg.samples[0].values[0].f
IndexError: list index (0) out of range
```
It seems that the value array is empty. 
Can it be that the data is not stored correctly? Do you have an idea?

Thanks and best regards
Alexandra

**Comment by stv0g** [comment]
Hi @al3xa23,

just to check: Does this issue still exists?

**Comment by al3xa23** [comment]
Hi, I tried to replicate it and the issue does not occur anymore. So, I will close the issue
