### ISSUE TITLE
Card classes and Card factories are in same file

### ISSUE THREAD

**Issue by IgnoreWarnings** [VILLASframework/node#792]
To improve readability, clarity of intention and includes, every class should  generally be in its own file.
Therefore I would like to refactor all card factories into seperate files.
@stv0g Do you share this refactor Idea?

**Comment by stv0g** [comment]
My I am not sure. There are more places where we use factories. E.g for all plugins: nodes, formats, API requests. I would keep them in the same file as it's clearer that they belong together.
