### ISSUE TITLE
Shared Memory Example not working

### ISSUE THREAD

**Issue by morje-datta** [VILLASframework/node#798]
Hello,

Current I have install fedora 36 install on my desktop,I have read the documentation regarding villas node, i am trying for shared memory example but seem its not working for me. i have follow the same.when i run villas-shmem client there no data present. for more details i have added the screen shot.

Example
https://villas.fein-aachen.org/docs/node/nodes/shmem

![Screenshot from 2024-07-24 18-02-54](https://github.com/user-attachments/assets/bb5cda69-fa5d-4411-b6de-85203bedf176)

**Comment by stv0g** [comment]
The invocation of villas-Sheen is missing mandatory arguments as the usage message indicates. You will need to pass the name of the shared memory segments.

Can you please also provide the config file used by villas-node?

**Comment by morje-datta** [comment]
Hello,

I have added the share memory name as the argument but its saying segmentation fault. For reference i have added the screenshot.
configuration file: https://github.com/VILLASframework/node/blob/master/etc/examples/nodes/shmem.conf

Example that i have run is https://github.com/VILLASframework/node/blob/master/clients/shmem/villas-shmem.cpp

![Screenshot from 2024-07-29 11-26-28](https://github.com/user-attachments/assets/048b89db-ee75-432e-b0a0-76083943184b)

**Comment by stv0g** [comment]
The example `shmem.conf` config file is made in such a way that it tests a loopback connection. Hence, the settings `nodes.shmem_node.{in,out}.name` are the same (`sn1_in`) in both directions.

If you want to test the shared memory connection between a VILLASnode instance (`villas-ndoe`) and the test program `villas-shmem`, you will need to use different names for each direction and also pass those different names as command line arguments to `villas-shmem`.

Please also note, that the shared memory node-type has note been used that much in the past.
Are you sure that you really need it? Maybe socket-based communication e.g. `mqtt` or plain UDP `socket` are better suited for your use case.

**Comment by morje-datta** [comment]
actually i want to import/export data to DPSIM for that reason i am using the share memory. so could you guide me how i can import/export data from DPSIM

**Comment by stv0g** [comment]
Ah I see. The interface between VILLASnode and DPsim is no longer using the shared memory interface. This is obsolete. VILLASnode is now embedded into DPsim directly. I suggest you have a look at the DPsim examples. Especially those using the `VillasInterface`.

**Comment by stv0g** [comment]
Closed due to lack of feedback.
